Create: Benefit Section
alizul01/polinema-innovation-tribe pull request #20
Opened 2023-01-01 08:23 UTC by alizul01

and give some anchor tag to build by section

2023-01-01 08:49 UTC, elianiva requested changes

2023-01-01 08:49 UTC, elianiva commented on src/components/Card.tsx
> +type cardType = {
prefer PascalCase buat type/interface

```suggestion
type CardType = {
```

2023-01-01 08:49 UTC, elianiva commented on src/components/Card.tsx
> +export default Card
mending named export aja sih menurutku, biar lebih lancar autocompletenya pas import

2023-01-01 08:49 UTC, elianiva commented on src/parts/HomePage/BenefitSection.tsx
> +type cardType = {
ini juga, PascalCase aja

2023-01-01 08:49 UTC, elianiva commented on src/parts/HomePage/BenefitSection.tsx
> +import LightBulb from "~icons/heroicons/light-bulb-solid";
rasanya enak dikasih suffix Icon buat nandain kalo ini itu icon, biar lebih jelas

2023-01-01 08:49 UTC, elianiva commented on src/parts/HomePage/ContributorSection.tsx
> +            <a href={contributors.githubUrl}>
lupa belom dikasih key

2023-01-01 08:55 UTC, alizul01 commented
Alright sepertinya sudah aman

2023-01-01 08:57 UTC, merged

2024-05-24 05:30 UTC, dcalibri commented
what is this?